name: "Marp to GitHub Pages"

on:
  push:
    branches: [ main ]  # Assicurati che questo corrisponda al tuo branch principale
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    
    - name: Install Marp CLI
      run: npm install -g @marp-team/marp-cli
    
    - name: Convert Markdown to HTML
      run: |
        ls -la  # Lista i file nella directory
        cat introduction.md  # Mostra il contenuto del file introduction.md
        cat versioncontrol.md  
        marp --version  # Mostra la versione di Marp
        marp introduction.md -o index.html --verbose  
        marp versioncontrol.md -o versioncontrol.html --verbose 
        marp firstwebpage.md -o firstwebpage.html --verbose   
        marp train4hackaton.md -o train4hackaton.html --verbose 
        marp webaudioprogramming.md -o webaudioprogramming.html --verbose
        marp hack2instructions.md -o hack2instructions.html --verbose
        marp embeddedprogramming.md -o embeddedprogramming.html --verbose
        marp embeddedprogramming2.md -o embeddedprogramming2.html --verbose          
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
